### ISSUE TITLE
通報時のカットイン

### ISSUE THREAD

**Issue by shisoromi** [makimaki-soft/bokupan#24]

**Comment by sryoji** [comment]
↓のPRで対応。
https://github.com/makimaki-soft/bokupan/pull/44

カットイン用の画像がまだ

**Comment by sryoji** [comment]
画像追加すみ。resourece.jsを修正する。

**Comment by sryoji** [comment]
↓のPRで対応
https://github.com/makimaki-soft/bokupan/pull/55
